language: rust
sudo: true
dist: xenial

install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get -y update
  - sudo apt-get -y install gcc-arm-embedded


cache: apt

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly
fast_finish: true

# install:
#   - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
#   - sudo apt-get -y update
#   - sudo apt-get -y install gcc-arm-embedded

script:
  - cargo build -vv
  - cargo test -vv
  - make